import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = '7273476577:AAGK0cjQDPy75jm-FgmDHhbi-7kBw1sSmTw'

(
    WAITING_FOR_AMOUNT,
    WAITING_FOR_CATEGORY,
    WAITING_FOR_DESCRIPTION,
    WAITING_FOR_INCOME_AMOUNT,
    WAITING_FOR_INCOME_SOURCE,
    WAITING_FOR_INCOME_DESCRIPTION,
    WAITING_FOR_EXPENSE_DATE,
    WAITING_FOR_INCOME_DATE,
    WAITING_FOR_SEARCH_QUERY,
    WAITING_FOR_BULK_TYPE,
    WAITING_FOR_BULK_DATA,
    WAITING_FOR_BULK_DELETE_TYPE,
    WAITING_FOR_BULK_DELETE_IDS
) = range(13)

BACK_BUTTON_TEXT = "⬅️ Назад"

